export enum LoLRegion {
  // NA = "na1",
  // EUW = "euw1",
  // EUNE = "eun1",
  // KR = "kr",
  // BR = "br1",
  // LAN = "la1",
  // LAS = "la2",
  // JP = "jp1",
  // OCE = "oc1",
  // TR = "tr1",
  // RU = "ru",
  NA = "na",
  EUW = "euw",
  EUNE = "eune",
  KR = "kr",
  BR = "br",
  LAN = "lan",
  LAS = "las",
  JP = "jp",
  OCE = "oce",
  TR = "tr",
  RU = "ru",
}